mv batch_run.sh.1.err ./boxing_v1.err
mv batch_run.sh.2.err ./ice_hockey_v1.err
mv batch_run.sh.3.err ./joust_v2.err
mv batch_run.sh.4.err ./mario_bros_v2.err
mv batch_run.sh.5.err ./warlords_v2.err
mv batch_run.sh.6.err ./foozpong_v1.err
mv batch_run.sh.7.err ./pong_v1.err
mv batch_run.sh.8.err ./combat_plane_v1.err
mv batch_run.sh.9.err ./combat_tank_v1.err
mv batch_run.sh.10.err ./double_dunk_v2.err
mv batch_run.sh.11.err ./entombed_competitive_v2.err
mv batch_run.sh.12.err ./entombed_cooperative_v2.err
mv batch_run.sh.13.err ./quadrapong_v2.err
mv batch_run.sh.14.err ./basketball_pong_v1.err
mv batch_run.sh.15.err ./volleyball_pong_v1.err
mv batch_run.sh.16.err ./flag_capture_v1.err
mv batch_run.sh.17.err ./maze_craze_v2.err
mv batch_run.sh.18.err ./space_invaders_v1.err
mv batch_run.sh.19.err ./space_war_v1.err
mv batch_run.sh.20.err ./surround_v1.err
mv batch_run.sh.21.err ./tennis_v2.err
mv batch_run.sh.22.err ./wizard_of_wor_v2.err
mv batch_run.sh.23.err ./video_checkers_v2.err
mv batch_run.sh.24.err ./othello_v2.err
