workon main_env && python independent_atari.py boxing_v1 rainbow
workon main_env && python independent_atari.py ice_hockey_v1 rainbow
workon main_env && python independent_atari.py joust_v2 rainbow
workon main_env && python independent_atari.py mario_bros_v2 rainbow
workon main_env && python independent_atari.py warlords_v2 rainbow
workon main_env && python independent_atari.py foozpong_v1 rainbow
workon main_env && python independent_atari.py pong_v1 rainbow
workon main_env && python independent_atari.py combat_plane_v1 rainbow
workon main_env && python independent_atari.py combat_tank_v1 rainbow
workon main_env && python independent_atari.py double_dunk_v2 rainbow
workon main_env && python independent_atari.py entombed_competitive_v2 rainbow
workon main_env && python independent_atari.py entombed_cooperative_v2 rainbow
workon main_env && python independent_atari.py quadrapong_v2 rainbow
workon main_env && python independent_atari.py basketball_pong_v1 rainbow
workon main_env && python independent_atari.py volleyball_pong_v1 rainbow
workon main_env && python independent_atari.py flag_capture_v1 rainbow
workon main_env && python independent_atari.py maze_craze_v2 rainbow
workon main_env && python independent_atari.py space_invaders_v1 rainbow
workon main_env && python independent_atari.py space_war_v1 rainbow
workon main_env && python independent_atari.py surround_v1 rainbow
workon main_env && python independent_atari.py tennis_v2 rainbow
workon main_env && python independent_atari.py wizard_of_wor_v2 rainbow
workon main_env && python independent_atari.py video_checkers_v2 rainbow
workon main_env && python independent_atari.py othello_v2 rainbow
